import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/header"
import BurgerMenu from "@/components/burgermenu";

export const metadata: Metadata = {
  title: "Chatbot!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{height: '100vh', width: '100vw'}} className="h-screen w-screen relative">
      {/* <Header /> */}
        <BurgerMenu />
        {children}
      </body>
    </html>
  );
}
